// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/github/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/github/service.go -destination=internal/test/mocks/github_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	github "github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/infrastructure/github"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FetchRepositories mocks base method.
func (m *MockService) FetchRepositories() ([]github.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRepositories")
	ret0, _ := ret[0].([]github.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRepositories indicates an expected call of FetchRepositories.
func (mr *MockServiceMockRecorder) FetchRepositories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRepositories", reflect.TypeOf((*MockService)(nil).FetchRepositories))
}
