// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repositories/projects_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repositories/projects_repository.go -destination=internal/test/mocks/projects_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectsRepository is a mock of ProjectsRepository interface.
type MockProjectsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectsRepositoryMockRecorder is the mock recorder for MockProjectsRepository.
type MockProjectsRepositoryMockRecorder struct {
	mock *MockProjectsRepository
}

// NewMockProjectsRepository creates a new mock instance.
func NewMockProjectsRepository(ctrl *gomock.Controller) *MockProjectsRepository {
	mock := &MockProjectsRepository{ctrl: ctrl}
	mock.recorder = &MockProjectsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectsRepository) EXPECT() *MockProjectsRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockProjectsRepository) CreateOrUpdate(project entities.Project) (entities.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", project)
	ret0, _ := ret[0].(entities.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockProjectsRepositoryMockRecorder) CreateOrUpdate(project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockProjectsRepository)(nil).CreateOrUpdate), project)
}

// Delete mocks base method.
func (m *MockProjectsRepository) Delete(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectsRepositoryMockRecorder) Delete(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectsRepository)(nil).Delete), uuid)
}

// GetAll mocks base method.
func (m *MockProjectsRepository) GetAll() ([]entities.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]entities.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProjectsRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProjectsRepository)(nil).GetAll))
}
