// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSyncProjectsUseCase creates a new instance of MockSyncProjectsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncProjectsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncProjectsUseCase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSyncProjectsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSyncProjectsUseCase is an autogenerated mock type for the SyncProjectsUseCase type
type MockSyncProjectsUseCase struct {
	mock.Mock
}

type MockSyncProjectsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncProjectsUseCase) EXPECT() *MockSyncProjectsUseCase_Expecter {
	return &MockSyncProjectsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockSyncProjectsUseCase
func (_mock *MockSyncProjectsUseCase) Execute(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSyncProjectsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSyncProjectsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSyncProjectsUseCase_Expecter) Execute(ctx any) *MockSyncProjectsUseCase_Execute_Call {
	return &MockSyncProjectsUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockSyncProjectsUseCase_Execute_Call) Run(run func(ctx context.Context)) *MockSyncProjectsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSyncProjectsUseCase_Execute_Call) Return(err error) *MockSyncProjectsUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSyncProjectsUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context) error) *MockSyncProjectsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
