// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSupabaseService creates a new instance of MockSupabaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupabaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupabaseService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSupabaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSupabaseService is an autogenerated mock type for the SupabaseService type
type MockSupabaseService struct {
	mock.Mock
}

type MockSupabaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupabaseService) EXPECT() *MockSupabaseService_Expecter {
	return &MockSupabaseService_Expecter{mock: &_m.Mock}
}

// ReplaceAll provides a mock function for the type MockSupabaseService
func (_mock *MockSupabaseService) ReplaceAll(ctx context.Context, projects []entities.Project) error {
	ret := _mock.Called(ctx, projects)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.Project) error); ok {
		r0 = returnFunc(ctx, projects)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSupabaseService_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockSupabaseService_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - projects []entities.Project
func (_e *MockSupabaseService_Expecter) ReplaceAll(ctx any, projects any) *MockSupabaseService_ReplaceAll_Call {
	return &MockSupabaseService_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, projects)}
}

func (_c *MockSupabaseService_ReplaceAll_Call) Run(run func(ctx context.Context, projects []entities.Project)) *MockSupabaseService_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entities.Project
		if args[1] != nil {
			arg1 = args[1].([]entities.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSupabaseService_ReplaceAll_Call) Return(err error) *MockSupabaseService_ReplaceAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSupabaseService_ReplaceAll_Call) RunAndReturn(run func(ctx context.Context, projects []entities.Project) error) *MockSupabaseService_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}
