// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectsRepository creates a new instance of MockProjectsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectsRepository {
	mock := &MockProjectsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectsRepository is an autogenerated mock type for the ProjectsRepository type
type MockProjectsRepository struct {
	mock.Mock
}

type MockProjectsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectsRepository) EXPECT() *MockProjectsRepository_Expecter {
	return &MockProjectsRepository_Expecter{mock: &_m.Mock}
}

// CreateAll provides a mock function for the type MockProjectsRepository
func (_mock *MockProjectsRepository) CreateAll(projects []entities.Project) error {
	ret := _mock.Called(projects)

	if len(ret) == 0 {
		panic("no return value specified for CreateAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]entities.Project) error); ok {
		r0 = returnFunc(projects)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectsRepository_CreateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAll'
type MockProjectsRepository_CreateAll_Call struct {
	*mock.Call
}

// CreateAll is a helper method to define mock.On call
//   - projects []entities.Project
func (_e *MockProjectsRepository_Expecter) CreateAll(projects any) *MockProjectsRepository_CreateAll_Call {
	return &MockProjectsRepository_CreateAll_Call{Call: _e.mock.On("CreateAll", projects)}
}

func (_c *MockProjectsRepository_CreateAll_Call) Run(run func(projects []entities.Project)) *MockProjectsRepository_CreateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []entities.Project
		if args[0] != nil {
			arg0 = args[0].([]entities.Project)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectsRepository_CreateAll_Call) Return(err error) *MockProjectsRepository_CreateAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectsRepository_CreateAll_Call) RunAndReturn(run func(projects []entities.Project) error) *MockProjectsRepository_CreateAll_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockProjectsRepository
func (_mock *MockProjectsRepository) DeleteAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectsRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockProjectsRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
func (_e *MockProjectsRepository_Expecter) DeleteAll() *MockProjectsRepository_DeleteAll_Call {
	return &MockProjectsRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll")}
}

func (_c *MockProjectsRepository_DeleteAll_Call) Run(run func()) *MockProjectsRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectsRepository_DeleteAll_Call) Return(err error) *MockProjectsRepository_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectsRepository_DeleteAll_Call) RunAndReturn(run func() error) *MockProjectsRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockProjectsRepository
func (_mock *MockProjectsRepository) GetAll() ([]entities.Project, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]entities.Project, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []entities.Project); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectsRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProjectsRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockProjectsRepository_Expecter) GetAll() *MockProjectsRepository_GetAll_Call {
	return &MockProjectsRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockProjectsRepository_GetAll_Call) Run(run func()) *MockProjectsRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectsRepository_GetAll_Call) Return(projects []entities.Project, err error) *MockProjectsRepository_GetAll_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectsRepository_GetAll_Call) RunAndReturn(run func() ([]entities.Project, error)) *MockProjectsRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
