// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectsRepository creates a new instance of MockProjectsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProjectsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProjectsRepository is an autogenerated mock type for the ProjectsRepository type
type MockProjectsRepository struct {
	mock.Mock
}

type MockProjectsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectsRepository) EXPECT() *MockProjectsRepository_Expecter {
	return &MockProjectsRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockProjectsRepository
func (_mock *MockProjectsRepository) GetAll(ctx context.Context) ([]entities.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectsRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProjectsRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectsRepository_Expecter) GetAll(ctx any) *MockProjectsRepository_GetAll_Call {
	return &MockProjectsRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockProjectsRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockProjectsRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectsRepository_GetAll_Call) Return(projects []entities.Project, err error) *MockProjectsRepository_GetAll_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectsRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]entities.Project, error)) *MockProjectsRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAndCreateAll provides a mock function for the type MockProjectsRepository
func (_mock *MockProjectsRepository) ResetAndCreateAll(ctx context.Context, projects []entities.Project) error {
	ret := _mock.Called(ctx, projects)

	if len(ret) == 0 {
		panic("no return value specified for ResetAndCreateAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.Project) error); ok {
		r0 = returnFunc(ctx, projects)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectsRepository_ResetAndCreateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAndCreateAll'
type MockProjectsRepository_ResetAndCreateAll_Call struct {
	*mock.Call
}

// ResetAndCreateAll is a helper method to define mock.On call
//   - ctx context.Context
//   - projects []entities.Project
func (_e *MockProjectsRepository_Expecter) ResetAndCreateAll(ctx any, projects any) *MockProjectsRepository_ResetAndCreateAll_Call {
	return &MockProjectsRepository_ResetAndCreateAll_Call{Call: _e.mock.On("ResetAndCreateAll", ctx, projects)}
}

func (_c *MockProjectsRepository_ResetAndCreateAll_Call) Run(run func(ctx context.Context, projects []entities.Project)) *MockProjectsRepository_ResetAndCreateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entities.Project
		if args[1] != nil {
			arg1 = args[1].([]entities.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectsRepository_ResetAndCreateAll_Call) Return(err error) *MockProjectsRepository_ResetAndCreateAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectsRepository_ResetAndCreateAll_Call) RunAndReturn(run func(ctx context.Context, projects []entities.Project) error) *MockProjectsRepository_ResetAndCreateAll_Call {
	_c.Call.Return(run)
	return _c
}
