// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cthiagoodev/thiagoodev-portfolio/services/projects_sync/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectsGateway creates a new instance of MockProjectsGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectsGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectsGateway {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProjectsGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProjectsGateway is an autogenerated mock type for the ProjectsGateway type
type MockProjectsGateway struct {
	mock.Mock
}

type MockProjectsGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectsGateway) EXPECT() *MockProjectsGateway_Expecter {
	return &MockProjectsGateway_Expecter{mock: &_m.Mock}
}

// PublishProjects provides a mock function for the type MockProjectsGateway
func (_mock *MockProjectsGateway) PublishProjects(ctx context.Context, projects []entities.Project) error {
	ret := _mock.Called(ctx, projects)

	if len(ret) == 0 {
		panic("no return value specified for PublishProjects")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.Project) error); ok {
		r0 = returnFunc(ctx, projects)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectsGateway_PublishProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishProjects'
type MockProjectsGateway_PublishProjects_Call struct {
	*mock.Call
}

// PublishProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - projects []entities.Project
func (_e *MockProjectsGateway_Expecter) PublishProjects(ctx any, projects any) *MockProjectsGateway_PublishProjects_Call {
	return &MockProjectsGateway_PublishProjects_Call{Call: _e.mock.On("PublishProjects", ctx, projects)}
}

func (_c *MockProjectsGateway_PublishProjects_Call) Run(run func(ctx context.Context, projects []entities.Project)) *MockProjectsGateway_PublishProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entities.Project
		if args[1] != nil {
			arg1 = args[1].([]entities.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectsGateway_PublishProjects_Call) Return(err error) *MockProjectsGateway_PublishProjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectsGateway_PublishProjects_Call) RunAndReturn(run func(ctx context.Context, projects []entities.Project) error) *MockProjectsGateway_PublishProjects_Call {
	_c.Call.Return(run)
	return _c
}
