services:
  projects-sync-db:
    image: postgres:18.6
    container_name: projects_sync_db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  projects-sync-migrator:
    image: migrate/migrate:latest
    container_name: projects-sync-migrator
    volumes:
      - ./migrations:/migrations:ro

    command:
      - -path=/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@projects-sync-db:5432/${POSTGRES_DB}?sslmode=disable
      - -verbose
      - up

    depends_on:
      projects-sync-db:
        condition: service_healthy

volumes:
  postgres_data:
